fix: vao-prod_update-resources
SocialGouv/vao pull request #314
Opened 2024-07-05 14:24 UTC by igorrenquin

- remove autoscale. feature included by default in kontinuous
- adjust requests, limits for :
  - frontend-usagers
  - backend
  - frontend-bo
  - cnpg

[VAO Tableau de bord](https://grafana-ovh.fabrique.social.gouv.fr/d/d4b333e0-3f10-46aa-8155-cb6e4c16eca9/tableau-de-bord-vao?orgId=1)

2024-07-05 14:29 UTC, matmut7 approved these changes

2024-07-05 14:30 UTC, igorrenquin commented
@achauve je te laisse merger et déployer.

2024-09-24 09:27 UTC, iNeoO commented
@achauve @igorrenquin Qu'est ce que vous voulez qu'on fasse de ça ?

2024-09-24 09:32 UTC, igorrenquin commented
> @achauve @igorrenquin Qu'est ce que vous voulez qu'on fasse de ça ?

Dans l'idéale l'appliquer.
Je te laisse comparer l'utilisation des ressources ce qui est actuellement consommé à ce que je propose de mettre à jour.

https://grafana-ovh.fabrique.social.gouv.fr/d/d4b333e0-3f10-46aa-8155-cb6e4c16eca9/tableau-de-bord-vao?orgId=1

2024-09-25 08:46 UTC, achauve commented
@igorrenquin désolé je n'avais pas vu ta PR, j'ai trop de notifs github du coup je ne les suis pas. Hésite pas à ping sur mattermost quand il y a besoin.

En fait il ne faudrait pas changer les valeurs de requests et limits dans le fichier `env/prod/values.yaml` mais le faire directement à la racine dans le fichier `values.yaml` global pour les 3 environnements. Ca permettrait d'économiser aussi beaucoup en dev et preprod.

Par ailleurs qu'est-ce que tu veux dire par l'autoscale est déjà géré par kontinuous ? tu veux dire que par défaut dans kontinuous autoscale est déjà à true ?

2024-09-25 08:47 UTC, achauve requested changes
Passer la modif de requests et limits dans le fichier values global

2024-10-07 08:40 UTC, achauve commented
Intégré sur main dans https://github.com/SocialGouv/vao/commit/da2cc70be999cf64bd721cb0ab46712ee8314829
J'ai baissé les limites sur nginx qui ne consomme vraiment rien (pour les frontends)

2024-10-07 08:41 UTC, closed without merging